name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip libxml2-dev libxslt-dev libffi-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework selenium robotframework-seleniumlibrary webdrivermanager

      - name: Install Chrome and ChromeDriver
        run: |
          # Install Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Install ChromeDriver using webdrivermanager (que irá detectar a versão correta)
          python -m webdrivermanager chrome --linkpath /usr/local/bin
          
          # Verify installations
          google-chrome --version
          chromedriver --version

      - name: Run Robot Framework tests
        run: |
          mkdir -p results
          robot \
            --outputdir results \
            --variable HEADLESS:True \
            --variable BROWSER:chrome \
            --variable URL:https://magento.softwaretestingboard.com/ \
            --log log.html \
            --report report.html \
            --output output.xml \
            tests/
          
          # Generate consolidated report
          rebot --outputdir results results/output.xml

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-test-results
          path: results/
          retention-days: 7