name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium and WebDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Set environment variables for Chromium
        run: |
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "ROBOT_BROWSER=chrome" >> $GITHUB_ENV

      - name: Run Robot Framework tests
        run: |
          robot --outputdir results resources/tests/

      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: robot-results
          path: results/
